name: ci/cd project

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v3
      - name: congigure a node js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - name: installing dependecies
        run: |
          echo "running installing dependecies ......"
          npm install

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run linting test
        run: |
          echo "running linting test ......"
          sleep 10s

  dockerize:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: build docker image
        run: docker build -t shaloomniyibizi/node-app .
      - name: push image to docker hub
        run: docker push shaloomniyibizi/node-app

  securityCheck:
    needs: build
    name: security checks
    runs-on: ubuntu-latest
    steps:
      - name: check for security
        run: |
          echo "running securuty check 1 ......"
          sleep 5s
          echo "running securuty check 2 ......"
          sleep 5s
          echo "running securuty check 3 ......"
          sleep 5s
          echo "running securuty check 4 ......"
          sleep 5s

  deploy:
    name: deployment
    runs-on: ubuntu-latest
    needs: securityCheck
    steps:
      - name: Deployment an application
        run: |
          sleep 5s
          echo "deployment in progress ......"
